# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b064933d441c295a06d20e4415ed3117338fed45a0fc944b6496e397113483c417f57c93b65a5bc410fe26b4b402fb3db7befe0de93ce1058b54a381a504fb73

test:
  secret_key_base: ccaff9753ef4dcaec49e3b27e257f310d1922d126f90e094d65051ac4884346d8110028436609818adf9b548dad2bdd1b65548874dfc262b1656d790f5153fcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
